Create README.md
matthew-latanafrancia/clothing-care-app pull request #2
Opened 2023-07-29 22:53 UTC by qkstngus000

IM IINNNN

2023-07-29 22:55 UTC, matthew-latanafrancia approved these changes

2023-07-29 22:59 UTC, matthew-latanafrancia requested changes

2023-07-29 22:59 UTC, matthew-latanafrancia commented on README.md
> +Project Group: Matt Latanafrancia, Michael Ban, Madeline Carter
```suggestion
Project Group: Matthew Latanafrancia, Michael Ban, Madeline Carter
```

2023-07-30 00:20 UTC, qkstngus000 commented
MATTTHEWWWW

2023-07-30 00:28 UTC, matthew-latanafrancia approved these changes

2023-07-30 00:28 UTC, merged